-- AlterTable
ALTER TABLE `conversations`
    ADD COLUMN `last_intent` VARCHAR(191) NULL,
    ADD COLUMN `pending_action` ENUM('IDLE', 'WAITING_MEDICINE_NAME', 'WAITING_PRESENTATION', 'WAITING_QUANTITY', 'WAITING_CEP', 'WAITING_ADDRESS_NUMBER', 'WAITING_CONFIRMATION', 'WAITING_PIX') NOT NULL DEFAULT 'IDLE',
    ADD COLUMN `last_medicine` VARCHAR(191) NULL,
    ADD COLUMN `selected_presentation` JSON NULL,
    ADD COLUMN `candidate_options` JSON NULL;
