// Curated retail spellings only. Never apply fuzzy substitutions to medicines.
export const RETAIL_SEARCH_ALIASES: Record<string, string[]> = {
  "soro fisiologico": ["soros fisiologicos"],
  gaze: ["gazes"],
  esparadrapo: ["esparadrapos"],
  termometro: ["termometros"],
  gillette: ["gilete", "giletes", "gilette", "gilet", "gillett", "gilletes"],
  prestobarba: ["presto barba", "presto-barba", "prestobarbas"],
  mach3: ["mach 3", "mach-3"],
  shampoo: ["xampu", "xampus", "shampu", "shampo", "shampoos", "shampoing"],
  condicionador: ["condicionadores", "condisionador"],
  sabonete: ["sabonetes"],
  desodorante: ["desodorantes", "desodorant", "desodorate"],
  "creme dental": ["pasta de dente", "pasta de dentes", "pasta dental", "pasta dente", "cremes dentais"],
  "escova dental": ["escova de dente", "escova de dentes", "escovas de dente", "escovas de dentes", "escovas dentais"],
  "fio dental": ["fios dentais"],
  "enxaguante bucal": ["enxaguantes bucais", "enxaguante bocal", "enxaguatorio bucal"],
  "lenco umedecido": ["lencos umedecidos", "lencinhos umedecidos", "lencinho umedecido", "toalhas umedecidas", "toalha umedecida"],
  cotonete: ["cotonetes", "hastes flexiveis", "haste flexivel"],
  preservativo: ["camisinha", "camisinhas", "preservativos", "condom"],
  fralda: ["fraldas"],
  absorvente: ["absorventes", "absovente"],
  "protetor solar": ["protetores solares", "filtro solar"],
  hidratante: ["hidratantes"],
  "aparelho de barbear": ["aparelhos de barbear", "aparelho barbear"],
  "lamina de barbear": ["laminas de barbear", "lamina barbear"],
  refil: ["refis"],
  "roll-on": ["roll on", "rollon"],
  aerosol: ["aerossol"],
  johnson: ["johnson's", "johnsons", "johnson s"],
  "oral-b": ["oral b", "oralb"],
  "k-y": ["ky", "k y"],
  tresemme: ["treseme", "tresseme"],
  mamypoko: ["mamy poko"],
  nivea: ["niveia"],
  sensodyne: ["sensodine"],
  colgate: ["colgatte"],
  "head & shoulders": ["head shoulders", "head and shoulders"],
};

// Explicit product types take precedence over a brand shared by several types.
export const RETAIL_CATEGORY_TERMS: Record<string, string[]> = {
  "soro fisiologico": ["soro fisiologico", "solucao fisiologica"],
  gaze: ["gaze"],
  esparadrapo: ["esparadrapo"],
  termometro: ["termometro"],
  "agua oxigenada": ["agua oxigenada"],
  "lenco umedecido": ["lenco umedecido"],
  "creme dental": ["creme dental", "gel dental", "dentifricio"],
  "escova de dente": ["escova dental"],
  "enxaguante bucal": ["enxaguante bucal", "antisseptico bucal"],
  "fio dental": ["fio dental", "fita dental"],
  "protetor solar": ["protetor solar"],
  lubrificante: ["gel lubrificante", "lubrificante"],
  shampoo: ["shampoo"],
  condicionador: ["condicionador"],
  sabonete: ["sabonete"],
  desodorante: ["desodorante", "antitranspirante"],
  absorvente: ["absorvente", "protetor diario"],
  preservativo: ["preservativo"],
  fralda: ["fralda"],
  hidratante: ["creme hidratante", "hidratante"],
  algodao: ["algodao"],
  cotonete: ["cotonete"],
  gillette: ["aparelho de barbear", "lamina de barbear", "carga de barbear"],
  alcool: ["alcool"],
};
